apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgres-template
  title: Postgres Database
  description: Deploy a Postgres Database to an existing namespace
  tags:
    - application-components
    - postgres
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Postgres Database
      required:
        - namespace
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: my-postgres-database
          ui:field: EntityNamePicker
          maxLength: 18
        namespace:
          title: Namespace
          type: string
          description: Namespace to which the Postgres database instance will be deployed
  steps:
    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: {{ '${{ parameters.component_id }}' }}
          source_repository_gitops: https://{{ gitlab_host }}/{{ '${{ user.entity.metadata.name }}' }}/{{ '${{parameters.component_id}}' }}-gitops.git
          owner: {{ '${{ user.entity.metadata.name }}' }}
          namespace: {{ '${{ parameters.namespace }}' }}
          gitops_namespace: {{ rhdh_gitops_namespace }}
          gitops_project: {{ rhdh_gitops_project }}
          git_host: {{ gitlab_host }}
          git_destination: {{ '${{ user.entity.metadata.name }}' }}/{{ '${{ parameters.component_id }}' }}-gitops
        targetPath: {{ './${{ user.entity.metadata.name }}-${{parameters.component_id}}-gitops' }}

    - id: publish
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "{{ gitlab_host }}?owner={{ '${{ user.entity.metadata.name }}' }}&repo={{ '${{parameters.component_id}}' }}-gitops"
        repoVisibility: public
        defaultBranch: main
        title: gitops resources for {{ '${{ parameters.component_id }}' }}
        description: gitops resources for {{ '${{ parameters.component_id }}' }}
        sourcePath: {{ './${{ user.entity.metadata.name }}-${{parameters.component_id}}-gitops' }}

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: {{ '${{ user.entity.metadata.name }}-${{ parameters.component_id }}' }}-bootstrap
        argoInstance: main
        namespace: {{ rhdh_gitops_namespace }}
        repoUrl: https://{{ gitlab_host }}/{{ '${{ user.entity.metadata.name }}' }}/{{ '${{ parameters.component_id }}' }}-gitops.git
        path: 'argocd/'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: {{ '${{ steps.publish.output.repoContentsUrl }}' }}
        catalogInfoPath: "/rhdh/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: {{ '${{ steps.publish.output.remoteUrl }}' }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: {{ '${{ steps.register.output.entityRef }}' }}
